services:
  app:
    container_name: dclinica-node16
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - '127.0.0.1:3004:3004'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ./public:/app/public
    #   - ./:/app
    #   - /app/node_modules
