#!/bin/bash

set -e

echo "docker compose down --remove-orphans"
docker compose down --remove-orphans --volumes --rmi local
sleep 1

# echo "docker compose down 'docker ps -qa'"
# docker rm -f $(docker ps -qa)
# sleep 1

echo "docker compose up -d"
docker compose up -d --build

echo "docker compose ps"
docker compose ps
